// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQnpXOQrDcPcYKYXnNTe7oYHVZjI1Cgao',
    appId: '1:5283983774:web:4535525752fb33f4efa68f',
    messagingSenderId: '5283983774',
    projectId: 'crud-51488',
    authDomain: 'crud-51488.firebaseapp.com',
    storageBucket: 'crud-51488.appspot.com',
    measurementId: 'G-ZE8EB0NP23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBVuctSecdAEzLrglIf3vwrDE1tW6BIME',
    appId: '1:5283983774:android:79981a9caae42f58efa68f',
    messagingSenderId: '5283983774',
    projectId: 'crud-51488',
    storageBucket: 'crud-51488.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL5NYieyHNWpq3jebJ_XPFu8cWOp1xfZU',
    appId: '1:5283983774:ios:5fce2d98145aa7a3efa68f',
    messagingSenderId: '5283983774',
    projectId: 'crud-51488',
    storageBucket: 'crud-51488.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL5NYieyHNWpq3jebJ_XPFu8cWOp1xfZU',
    appId: '1:5283983774:ios:cc013af93d7e53a7efa68f',
    messagingSenderId: '5283983774',
    projectId: 'crud-51488',
    storageBucket: 'crud-51488.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
